### ISSUE TITLE
テストコードの作成

### ISSUE THREAD

**Issue by tako-t-t-1046** [mori07/group_d_2016_gem#9]
それぞれのメソッドについて、テストコードを作成する。

例
def test_作成したメソッド
    assert_equal([-21, -3, 0, 1, 4, 10, 10000], 作成したメソッド [0, -3, 10, 1, 4, 10000, -21])
end

**Comment by tako-t-t-1046** [comment]
#13  マージソートについて簡単なテストコードを作成しました。

**Comment by mori07** [comment]
#19 にてクイックソートのテストコードを追加しました。
TravisCIでの自動テストも通過済みとなります。

**Comment by tako-t-t-1046** [comment]
バブルソート・セレクトソートについても、テスト通過していることを確認しました。
